# Generated by Django 5.1.2 on 2024-11-05 10:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Televisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=10)),
                ('pulgadas', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=20)),
                ('banco', models.CharField(choices=[('Caixa', 'Caixa'), ('BBVA', 'BBVA'), ('UNICAJA', 'UNICAJA'), ('ING', 'ING')], max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='televisores.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, 'Muy malo'), (2, 'Malo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Muy bueno')], default=5)),
                ('comentarios', models.TextField()),
                ('fecha_voto', models.DateField(default=django.utils.timezone.now)),
                ('televisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='televisores.televisor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='televisores.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuarios_televisores',
            field=models.ManyToManyField(related_name='usuarios_votantes', through='televisores.Votacion', to='televisores.televisor'),
        ),
    ]
